import React from 'react';
import Head from 'next/head';

export default function Sell() {
  return (
    <div>
      <Head>
        <title>Sell Car the easiest way</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-6xl mx-auto shadow-xl p-5 pt-5 rounded-xl bg-white">
        <form>
          <div className="flex flex-wrap justify-between p-3">
            <div className="w-1/2 pr-1">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                htmlFor="year"
              >
                Year
              </label>
              <input
                type="text"
                className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-600 focus:bg-white p-2"
                aria-placeholder="Enter your Year"
                id="year"
              />
            </div>
            <div className="w-1/2 pl-1">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                htmlFor="make"
              >
                Make
              </label>
              <input
                type="text"
                aria-placeholder="Enter your Make"
                id="make"
                className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
              />
            </div>
          </div>
          <div className="flex flex-row justify-between p-3">
            <div className="w-full">
              <div>
                <label
                  className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                  htmlFor="model"
                >
                  Model
                </label>
                <input
                  type="text"
                  aria-placeholder="Enter your Model"
                  className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="model"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-row justify-between p-3">
            <div className="w-full">
              <div>
                <label
                  className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                  htmlFor="origin"
                >
                  Origin
                </label>
                <input
                  type="text"
                  aria-placeholder="Enter your Car's Origin"
                  className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="origin"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-row p-3">
            <div className="w-1/2 pr-1">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                htmlFor="city"
              >
                City
              </label>
              <input
                type="text"
                aria-placeholder="Enter city "
                placeholder="Enter city "
                className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                id="city"
              />
            </div>
            <div className="w-1/2 pl-1">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                htmlFor="mileage"
              >
                Mileage
              </label>
              <input
                type="number"
                aria-placeholder="Enter mileage"
                placeholder="Enter mileage"
                className="w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                id="mileage"
              />
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3 "
                htmlFor="enginetype"
              >
                Engine Type
              </label>
              <div className="relative">
                <select
                  className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="enginetype"
                >
                  <option default>----- Select Engine type-----</option>
                  <option value="petrol">Petrol</option>
                  <option value="diesel">Diesel</option>
                  <option value="hybrid">Hybrid</option>
                  <option value="cng">CNG</option>
                  <option value="electric">Electric</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3 "
                htmlFor="color"
              >
                Color
              </label>
              <div className="relative">
                <select
                  className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="color"
                >
                  <option default>----- Select Color of your car-----</option>
                  <option value="white">White</option>
                  <option value="silver">Silver</option>
                  <option value="black">Black</option>
                  <option value="gray">Gray</option>
                  <option value="blue">Blue</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3 "
                htmlFor="transmissiontype"
              >
                Transmission Type
              </label>
              <div className="relative">
                <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500">
                  <option default>----- Select Transmission type-----</option>
                  <option value="manual">Manual</option>
                  <option value="automatic">Automatic</option>
                  <option value="CVT">CVT Variant</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3 "
                htmlFor="cartype"
              >
                Car Type
              </label>
              <div className="relative">
                <select
                  className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="cartype"
                >
                  <option default>----- Select Car type-----</option>
                  <option value="owner">SUV/Crossover</option>
                  <option value="dealer">Sedan</option>
                  <option value="certified">Pickup Truck</option>
                  <option value="certified">Convertible</option>
                  <option value="certified">Coupe</option>
                  <option value="certified">Hatchback</option>
                  <option value="certified">Van</option>
                  <option value="certified">Truck</option>
                  <option value="certified">Bus</option>
                  <option value="certified">Other</option>
                  <option value="certified">Bike</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3 "
                htmlFor="registeredin"
              >
                Registered In
              </label>
              <div className="relative">
                <select
                  className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="registeredin"
                >
                  <option default>----- Select Registered City-----</option>
                  <option value="dubai">Dubai</option>
                  <option value="ajman">Ajman</option>
                  <option value="sharjah">Sharjah</option>
                  <option value="abudhabi">Abu Dhabi</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-row justify-between p-3">
            <label
              className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
              htmlFor="assembly"
            >
              Assembly
            </label>
            <div className="relative">
              <select
                className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                id="registeredin"
              >
                <option default>----- Select Assembly Origin-----</option>
                <option value="local">Local</option>
                <option value="imported">Imported</option>
              </select>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full">
              <label
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 xs:mt-3"
                htmlFor="sellertype"
              >
                Seller Type
              </label>
              <div className="relative">
                <select
                  className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-4 rounded leading-tight focus:outline-none focus:border-gray-500"
                  id="sellertype"
                >
                  <option default>----- Select Seller type-----</option>
                  <option value="owner">Owner</option>
                  <option value="dealer">Dealer</option>
                  <option value="certified">
                    Dealership/Certified Pre-owned
                  </option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap p-3">
            <div className="w-full px-3 mb-6 xs:mb-0 mt-2">
              <button
                type="submit"
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full xs:text-xs"
              >
                Submit
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
